import { z } from "zod";
import type { SkillManifest } from "@quickdeployai/skill-registry-schemas";

export const OPENAPI_2_AGENT_SKILLS_ENGINE = "openapi-2-agent-skills";

const WRITE_METHODS = new Set(["POST", "PUT", "PATCH", "DELETE"]);

const OpenApiParameterSchema = z
  .object({
    name: z.string(),
    in: z.string(),
    required: z.boolean().optional(),
    description: z.string().optional(),
  })
  .catchall(z.unknown());

const OpenApiOperationSchema = z
  .object({
    operationId: z.string().optional(),
    summary: z.string().optional(),
    description: z.string().optional(),
    parameters: z.array(OpenApiParameterSchema).optional(),
  })
  .catchall(z.unknown());

const OpenApiDocumentSchema = z
  .object({
    openapi: z.string().optional(),
    swagger: z.string().optional(),
    info: z.object({ title: z.string().optional(), version: z.string().optional() }).catchall(z.unknown()).optional(),
    paths: z.record(z.string(), z.record(z.string(), z.unknown())).default({}),
  })
  .catchall(z.unknown());

export interface GeneratedSkillFiles {
  files: Record<string, string>;
}

/**
 * Generate the endpoint-reference bundle for an API skill. The manifest's
 * `spec.select.requests` picks which operations surface; when
 * `spec.config.defaults.mode` is "read-only", selecting a write method is an
 * error rather than a silent downgrade.
 */
export function generateSkillFiles(
  manifest: SkillManifest,
  sourceText: string,
): GeneratedSkillFiles {
  const document = OpenApiDocumentSchema.parse(JSON.parse(sourceText));
  const selected = manifest.spec.select?.requests;
  if (!selected || selected.length === 0) {
    throw new Error("openapi-2-agent-skills manifests must select at least one request.");
  }

  const mode = manifest.spec.config?.defaults?.["mode"];
  if (mode === "read-only") {
    const writes = selected.filter((request) => WRITE_METHODS.has(request.method));
    if (writes.length > 0) {
      throw new Error(
        `read-only mode forbids write selections: ${writes
          .map((request) => `${request.method} ${request.uriTemplate}`)
          .join(", ")}.`,
      );
    }
  }

  const title = document.info?.title ?? "API";
  const lines: string[] = [
    `# ${title} endpoint reference`,
    "",
    `Generated by ${OPENAPI_2_AGENT_SKILLS_ENGINE} from the manifest's digest-pinned OpenAPI source` +
      (document.info?.version ? ` (spec version ${document.info.version}).` : "."),
    "Do not edit by hand — re-run the importer to update.",
    "",
  ];

  const sorted = [...selected].sort((left, right) =>
    `${left.uriTemplate} ${left.method}`.localeCompare(`${right.uriTemplate} ${right.method}`),
  );

  for (const request of sorted) {
    const pathItem = document.paths[request.uriTemplate];
    const rawOperation = pathItem?.[request.method.toLowerCase()];
    if (rawOperation === undefined) {
      throw new Error(
        `Selected request ${request.method} ${request.uriTemplate} not found in the OpenAPI document.`,
      );
    }
    const operation = OpenApiOperationSchema.parse(rawOperation);
    const isWrite = WRITE_METHODS.has(request.method);

    lines.push(`## ${request.method} \`${request.uriTemplate}\`${isWrite ? " (write)" : ""}`, "");
    if (operation.summary) lines.push(operation.summary, "");
    if (isWrite) {
      lines.push(
        "> Destructive/write operation: summarize the exact change and get",
        "> explicit user confirmation before calling.",
        "",
      );
    }
    const parameters = operation.parameters ?? [];
    if (parameters.length > 0) {
      lines.push("| Parameter | In | Required | Description |", "| --- | --- | --- | --- |");
      for (const parameter of parameters) {
        lines.push(
          `| \`${parameter.name}\` | ${parameter.in} | ${parameter.required ? "yes" : "no"} | ${(parameter.description ?? "").replaceAll("\n", " ").trim()} |`,
        );
      }
      lines.push("");
    }
  }

  return {
    files: {
      "references/api-endpoints.md": `${lines.join("\n").trimEnd()}\n`,
    },
  };
}
