import { z } from "zod";
import type { SkillManifest } from "@quickdeployai/skill-registry-schemas";

export const DOCS_2_AGENT_SKILLS_ENGINE = "docs-2-agent-skills";

/**
 * The source document this importer consumes: a curated docs bundle. Pages
 * carry procedural help-center/product-docs content; csvMaps carry export
 * column maps (the absorbed csv-export-2-agent-skills source kind) with
 * per-column validation rules for reconciliation workflows.
 */
export const DocsBundleSchema = z.object({
  product: z.string().min(1),
  pages: z
    .array(
      z.object({
        title: z.string().min(1),
        url: z.string().min(1).optional(),
        content: z.string().min(1),
      }),
    )
    .default([]),
  csvMaps: z
    .array(
      z.object({
        name: z.string().min(1),
        description: z.string().min(1).optional(),
        columns: z
          .array(
            z.object({
              name: z.string().min(1),
              type: z.string().min(1),
              required: z.boolean().default(false),
              description: z.string().min(1).optional(),
              validation: z.string().min(1).optional(),
            }),
          )
          .min(1),
      }),
    )
    .default([]),
});
export type DocsBundle = z.infer<typeof DocsBundleSchema>;

export interface GeneratedSkillFiles {
  files: Record<string, string>;
}

/**
 * Generate reference files from a docs bundle. `spec.select.docGlobs`
 * filters page titles and csv map names with `*` wildcards; every glob must
 * match something so stale selections fail loudly.
 */
export function generateSkillFiles(
  manifest: SkillManifest,
  sourceText: string,
): GeneratedSkillFiles {
  const bundle = DocsBundleSchema.parse(JSON.parse(sourceText));
  const globs = manifest.spec.select?.docGlobs;
  if (!globs || globs.length === 0) {
    throw new Error("docs-2-agent-skills manifests must select at least one docGlob.");
  }

  const matchers = globs.map((glob) => ({ glob, regex: globToRegex(glob), matched: false }));
  const matches = (title: string): boolean => {
    let matched = false;
    for (const matcher of matchers) {
      if (matcher.regex.test(title)) {
        matcher.matched = true;
        matched = true;
      }
    }
    return matched;
  };

  const pages = bundle.pages.filter((page) => matches(page.title));
  const csvMaps = bundle.csvMaps.filter((map) => matches(map.name));

  const unmatched = matchers.filter((matcher) => !matcher.matched);
  if (unmatched.length > 0) {
    throw new Error(
      `docGlobs matched nothing in the bundle: ${unmatched.map((matcher) => matcher.glob).join(", ")}.`,
    );
  }

  const files: Record<string, string> = {};
  const header = (subject: string): string[] => [
    `# ${bundle.product}: ${subject}`,
    "",
    `Generated by ${DOCS_2_AGENT_SKILLS_ENGINE} from the manifest's pinned docs bundle.`,
    "Do not edit by hand — re-run the importer to update.",
    "",
  ];

  for (const page of pages) {
    const lines = header(page.title);
    if (page.url) lines.push(`Source: ${page.url}`, "");
    lines.push(page.content.trim());
    files[`references/docs-${slugify(page.title)}.md`] = `${lines.join("\n").trimEnd()}\n`;
  }

  for (const map of csvMaps) {
    const lines = header(`${map.name} export columns`);
    if (map.description) lines.push(map.description, "");
    lines.push("| Column | Type | Required | Description | Validation |", "| --- | --- | --- | --- | --- |");
    for (const column of map.columns) {
      lines.push(
        `| \`${column.name}\` | ${column.type} | ${column.required ? "yes" : "no"} | ${column.description ?? ""} | ${column.validation ?? ""} |`,
      );
    }
    lines.push(
      "",
      "Reject rows that violate a validation rule and report them by row",
      "number instead of silently skipping or coercing values.",
    );
    files[`references/export-${slugify(map.name)}.md`] = `${lines.join("\n").trimEnd()}\n`;
  }

  return { files };
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function globToRegex(glob: string): RegExp {
  const escaped = glob.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replaceAll("\\*", ".*");
  return new RegExp(`^${escaped}$`, "i");
}
