import {
  parse,
  print,
  type FieldDefinitionNode,
  type ObjectTypeDefinitionNode,
  type ObjectTypeExtensionNode,
} from "graphql";
import type { SkillManifest } from "@quickdeployai/skill-registry-schemas";

export const GRAPHQL_2_AGENT_SKILLS_ENGINE = "graphql-2-agent-skills";

export interface GeneratedSkillFiles {
  files: Record<string, string>;
}

/**
 * Generate the operation-reference bundle for a GraphQL API skill from SDL.
 * The manifest's `spec.select.graphqlOperations` picks root fields off the
 * Query/Mutation types; every selected mutation gets a safe-operation
 * checklist (mutations are writes by definition).
 */
export function generateSkillFiles(
  manifest: SkillManifest,
  sourceText: string,
): GeneratedSkillFiles {
  const selected = manifest.spec.select?.graphqlOperations;
  if (!selected || selected.length === 0) {
    throw new Error("graphql-2-agent-skills manifests must select at least one operation.");
  }

  const document = parse(sourceText);
  const roots: Record<"query" | "mutation", Map<string, FieldDefinitionNode>> = {
    query: new Map(),
    mutation: new Map(),
  };
  for (const definition of document.definitions) {
    if (definition.kind !== "ObjectTypeDefinition" && definition.kind !== "ObjectTypeExtension") {
      continue;
    }
    const node = definition as ObjectTypeDefinitionNode | ObjectTypeExtensionNode;
    const root =
      node.name.value === "Query" ? "query" : node.name.value === "Mutation" ? "mutation" : null;
    if (!root) continue;
    for (const field of node.fields ?? []) {
      roots[root].set(field.name.value, field);
    }
  }

  const missing = selected.filter((operation) => !roots[operation.type].has(operation.name));
  if (missing.length > 0) {
    throw new Error(
      `Selected operations missing from the schema: ${missing
        .map((operation) => `${operation.type}.${operation.name}`)
        .join(", ")}.`,
    );
  }

  const lines: string[] = [
    "# GraphQL operation reference",
    "",
    `Generated by ${GRAPHQL_2_AGENT_SKILLS_ENGINE} from the manifest's pinned SDL source.`,
    "Do not edit by hand — re-run the importer to update.",
    "",
  ];

  const sorted = [...selected].sort((left, right) =>
    `${left.type}.${left.name}`.localeCompare(`${right.type}.${right.name}`),
  );

  for (const operation of sorted) {
    const field = roots[operation.type].get(operation.name);
    if (!field) continue;
    const isMutation = operation.type === "mutation";

    lines.push(`## ${operation.type} \`${operation.name}\`${isMutation ? " (write)" : ""}`, "");
    if (field.description?.value) lines.push(field.description.value.trim(), "");

    lines.push("```graphql", print(field).trim(), "```", "");

    if (isMutation) {
      lines.push(
        "Safe-operation checklist before calling:",
        "",
        "1. Summarize the exact input object and the entities it changes.",
        "2. Get explicit user confirmation for this specific call.",
        "3. Run against a development store/sandbox unless the user explicitly opted into production.",
        "4. Check `userErrors` in the response and report failures instead of retrying blindly.",
        "",
      );
    }
  }

  return {
    files: {
      "references/graphql-operations.md": `${lines.join("\n").trimEnd()}\n`,
    },
  };
}
