import { z } from "zod";
import type { SkillManifest } from "@quickdeployai/skill-registry-schemas";

export const CLI_2_AGENT_SKILLS_ENGINE = "cli-2-agent-skills";

/**
 * The source document this importer consumes: a captured CLI help dump.
 * Capture it once against a known CLI version (`<binary> <command> --help`)
 * and commit or digest-pin it, so generation is deterministic and offline.
 */
export const CliHelpDumpSchema = z.object({
  binary: z.string().min(1),
  version: z.string().min(1).optional(),
  commands: z.record(z.string().min(1), z.string().min(1)),
});
export type CliHelpDump = z.infer<typeof CliHelpDumpSchema>;

export interface GeneratedSkillFiles {
  /** Skill-relative path (references/…) → file content. */
  files: Record<string, string>;
}

/**
 * Generate the command-reference bundle for a CLI skill. The manifest's
 * `spec.select.commands` picks which captured commands surface and flags the
 * destructive ones; every selected command must exist in the help dump.
 */
export function generateSkillFiles(
  manifest: SkillManifest,
  sourceText: string,
): GeneratedSkillFiles {
  const dump = CliHelpDumpSchema.parse(JSON.parse(sourceText));
  const selected = manifest.spec.select?.commands;
  if (!selected || selected.length === 0) {
    throw new Error("cli-2-agent-skills manifests must select at least one command.");
  }

  const missing = selected.filter((entry) => dump.commands[entry.command] === undefined);
  if (missing.length > 0) {
    throw new Error(
      `Selected commands missing from help dump: ${missing.map((entry) => entry.command).join(", ")}.`,
    );
  }

  const safe = selected.filter((entry) => !entry.destructive);
  const destructive = selected.filter((entry) => entry.destructive);

  const lines: string[] = [
    `# ${dump.binary} command reference`,
    "",
    `Generated by ${CLI_2_AGENT_SKILLS_ENGINE} from a captured help dump` +
      (dump.version ? ` (${dump.binary} ${dump.version}).` : "."),
    "Do not edit by hand — re-run the importer to update.",
    "",
    "## Safe commands (read-only or reversible)",
    "",
    ...safe.map((entry) => `- \`${dump.binary} ${entry.command}\``),
  ];

  if (destructive.length > 0) {
    lines.push(
      "",
      "## Destructive commands — explicit confirmation required",
      "",
      "Summarize the exact objects and amounts affected and wait for the user",
      "to confirm before running any of these:",
      "",
      ...destructive.map((entry) => `- \`${dump.binary} ${entry.command}\``),
    );
  }

  lines.push("", "## Command help", "");
  for (const entry of [...selected].sort((a, b) => a.command.localeCompare(b.command))) {
    lines.push(
      `### \`${dump.binary} ${entry.command}\`${entry.destructive ? " (destructive)" : ""}`,
      "",
      "```text",
      (dump.commands[entry.command] ?? "").trim(),
      "```",
      "",
    );
  }

  return {
    files: {
      "references/cli-commands.md": `${lines.join("\n").trimEnd()}\n`,
    },
  };
}
